[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = ["q"]
run = "plugin projects quit"
desc = "Save last project and exit"

[[mgr.prepend_keymap]]
on = ["P", "s"]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = ["P", "l"]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = ["P", "d"]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = ["P", "D"]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "plugin lazygit"
desc = "Lazygit"

[[mgr.prepend_keymap]]
on = ["R", "b"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin Menu"

[[mgr.prepend_keymap]]
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste (force)"

[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

[[mgr.prepend_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link (relative path)"

[[mgr.prepend_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

[[mgr.prepend_keymap]]
on = ["d", "d"]
run = "remove"
desc = "Delete selected files/folders"

[[mgr.prepend_keymap]]
on = ["d", "D"]
run = "remove --permanently"
desc = "Delete selected files/folders (permanently)"

[[mgr.prepend_keymap]]
on = ["d", "u"]
run = "plugin restore"
desc = "Restore last deleted files/folders"

[[mgr.prepend_keymap]]
on = ["d", "U"]
run = "plugin restore -- --interactive"
desc = "Restore last deleted files/folders (interactive)"

[[mgr.prepend_keymap]]
on = ["f"]
run = "plugin searchjump"
desc = "searchjump mode"
